"""A robot arm simulation package."""

from __future__ import annotations

from .canvas import SkelarmCanvas, SkelarmViewer
from .control import (
    ComputedTorque,
    Controller,
    InverseDynamicsFeedforwardPD,
    JointPD,
    JointReference,
    SampledJointReference,
    SampledTaskReference,
    TaskReference,
    TrackingController,
    ik_joint_reference,
    resolved_rate_joint_reference,
    simulate_controlled,
)
from .curves import PeriodicTaskReference, build_curve, curve_kinds, register_curve
from .dynamics import (
    compute_coriolis_gravity_vector,
    compute_forward_dynamics,
    compute_inverse_dynamics,
    compute_kinetic_energy,
    compute_kinetic_energy_rate,
    compute_mass_matrix,
    integrate_with_limits,
    simulate_robot,
)
from .filtering import (
    FILTERS,
    butterworth_lowpass,
    lowpass_first_order,
    moving_average,
    savitzky_golay,
    smooth,
)
from .interpolation import INTERPOLATORS, interpolate, resample_with_derivatives
from .kinematics import (
    IKResult,
    compute_coriolis_basis,
    compute_endpoint_acceleration,
    compute_endpoint_velocity,
    compute_forward_kinematics,
    compute_inverse_kinematics,
    compute_jacobian,
)
from .mpc import JointSpaceMPC
from .plotting import draw_skeleton, plot_trajectory
from .reaching import (
    AdaptiveReferenceShaping,
    EndpointController,
    OnlineReferenceShaping,
    PositionDependentShaping,
    TimeVaryingStiffness,
    VirtualSpringDamper,
    adaptive_shaping_ratio,
    shaping_ratio,
)
from .recording import StateLog
from .scenario import (
    ControllerBuilder,
    Scenario,
    Simulator,
    Task,
    active_target_index,
    apply_active_target,
    build_controller,
    controller_types,
    export_scenario_toml,
    load_reference_log,
    load_scenario,
    multi_target_specs,
    reference_builders,
    register_controller,
    register_reference_builder,
    register_task_type,
    rerun_log,
    run_scenario,
    scenario_from_config,
    scenario_from_log,
    task_types,
)
from .simulator import SimulatorCanvas, SkelarmSimulator
from .skeleton import Link, LinkProp, Skeleton
from .trajectory import Trajectory, evaluate_schedule

__all__ = [
    "FILTERS",
    "INTERPOLATORS",
    "AdaptiveReferenceShaping",
    "ComputedTorque",
    "Controller",
    "ControllerBuilder",
    "EndpointController",
    "IKResult",
    "InverseDynamicsFeedforwardPD",
    "JointPD",
    "JointReference",
    "JointSpaceMPC",
    "Link",
    "LinkProp",
    "OnlineReferenceShaping",
    "PeriodicTaskReference",
    "PositionDependentShaping",
    "SampledJointReference",
    "SampledTaskReference",
    "Scenario",
    "Simulator",
    "SimulatorCanvas",
    "SkelarmCanvas",
    "SkelarmSimulator",
    "SkelarmViewer",
    "Skeleton",
    "StateLog",
    "Task",
    "TaskReference",
    "TimeVaryingStiffness",
    "TrackingController",
    "Trajectory",
    "VirtualSpringDamper",
    "active_target_index",
    "adaptive_shaping_ratio",
    "apply_active_target",
    "build_controller",
    "build_curve",
    "butterworth_lowpass",
    "compute_coriolis_basis",
    "compute_coriolis_gravity_vector",
    "compute_endpoint_acceleration",
    "compute_endpoint_velocity",
    "compute_forward_dynamics",
    "compute_forward_kinematics",
    "compute_inverse_dynamics",
    "compute_inverse_kinematics",
    "compute_jacobian",
    "compute_kinetic_energy",
    "compute_kinetic_energy_rate",
    "compute_mass_matrix",
    "controller_types",
    "curve_kinds",
    "draw_skeleton",
    "evaluate_schedule",
    "export_scenario_toml",
    "hello",
    "ik_joint_reference",
    "integrate_with_limits",
    "interpolate",
    "load_reference_log",
    "load_scenario",
    "lowpass_first_order",
    "moving_average",
    "multi_target_specs",
    "plot_trajectory",
    "reference_builders",
    "register_controller",
    "register_curve",
    "register_reference_builder",
    "register_task_type",
    "rerun_log",
    "resample_with_derivatives",
    "resolved_rate_joint_reference",
    "run_scenario",
    "savitzky_golay",
    "scenario_from_config",
    "scenario_from_log",
    "shaping_ratio",
    "simulate_controlled",
    "simulate_robot",
    "smooth",
    "task_types",
]


def hello() -> str:
    """Return a greeting message from skelarm."""
    return "Hello from skelarm!"
